закончил разметку главной страницы
htmlacademy-htmlcss/1556781-sedona-29 pull request #2
Opened 2020-09-13 11:57 UTC by Anton971

2020-09-14 06:53 UTC, urazaev requested changes

2020-09-14 06:53 UTC, urazaev commented on index.html
>      <title>HTML Academy: Седона</title>
Обязательно прогони файл валидатором, на https://validator.w3.org/nu/
error нужно устранить, при этом warning допустимы.

2020-09-14 06:53 UTC, urazaev commented on index.html
> +          <li><a href="Hotels.html">Гостиницы</a></li>
файлы именовать будем в нижнем регистре и ссылки тоже ставить на них соответственно в нижнем регистре `href="Hotels.html"` замени на `href="hotels.html"` по этому сразу лучше.

2020-09-14 06:53 UTC, urazaev commented on index.html
> +    <header>
Не забудь разметить лого

2020-09-14 06:53 UTC, urazaev commented on index.html
> +        </li>
в списке элементы должны быть однородными, вот эта штука выглядит вообще лишней

2020-09-14 06:53 UTC, urazaev commented on index.html
> +          <h5>Жилье</h5>
Заголовки сделай все например третьего уровня и еще их не бывает больше чем `h6` то есть `h7` это уже косяк, на который валидатор и ругается тебе, собственно просто сделай их единобразно например третьего уровня.

2020-09-14 06:53 UTC, urazaev commented on index.html
> +      <li>
Тут список заканчивай и дальше уже элементы не должны в него входить, верстай их вне списка, потому что они структурно уже не идут как перечисление, по смыслу.

2020-09-14 06:53 UTC, urazaev commented on index.html
> +      <h13>Поиск гостиницы в Седоне</h13>
Кнопка

2020-09-14 06:53 UTC, urazaev commented on index.html
> +    <p><a href="blank.html">Website by</a></p>
Посмотри по ТЗ на какой адрес должна вести данная ссылка.

2020-09-18 12:10 UTC, Anton971 commented on index.html
>      <title>HTML Academy: Седона</title>
хорошо

2020-09-18 12:16 UTC, closed without merging